### ISSUE TITLE
Flatten nested loops

### ISSUE THREAD

**Issue by LordUbuntu** [naftaliharris/Abstract-Algebra#2]
Lines like [these](https://github.com/naftaliharris/Abstract-Algebra/blob/d2651cb1f0e422810f6fa2e9f5d1909abe99f24a/absalg/Group.py#L135) include nested loops that can be flattened/reduced by using the cartesian product function in the itertools modue that is otherwise used throughout the rest of the program. Would it be all-right if I went ahead and flattened those loops?

**Comment by naftaliharris** [comment]
Go ahead!  Just make sure the tests pass.
